# Site settings
title: Open Crumb
description: Cooking projects
baseurl: /

# Personal settings
# twitter: @opencrumb__

# Sass settings
sass:
  add_charset: true
  sass_dir: _sass
#  style: :compressed

# Post settings
permalink: /:title/
